baseURL = "https://www.theschooldesk.app/blog/"
languageCode = "en-us"
theme = "chunky-poster"
title = "School Desk"
publishDir = "out"

archetypeDir = "archetypes"
contentDir = "content"
data = "data"
layoutDir = "layouts"
staticDir = "static"
themesDir = "themes"

# Chunky Poster theme stuff
paginate = 2
footnoteReturnLinkContents = "^"

[menu]
[[menu.main]]
identifier = "home"
name = "Return to App ⇒"
url = "https://www.theschooldesk.app/dashboard/"
weight = 10

[taxonomies]
author = "authors"
tag = "tags"
category = "categories"

[params]
description = "Homeschool Planning Software Simplified"
share = true
homepageImage = "/blog/images/organizing.svg"
customCSS = ["school-desk.css"]

[params.social]
rss = true
